export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8080/api/v1',
  platformProviderApiBaseUrl: 'http://localhost:8080/api/v1',
  platformProviderJavaApiBaseUrl: 'http://localhost:8080/api/v1',
  platformProviderRoutesEndpointPath: '/routes',
  platformProviderStopsEndpointPath: '/stops',
  platformProviderUsersEndpointPath: '/users',
  platformProviderOrganizationsEndpointPath: '/organizations',
  platformProviderSignInEndpointPath: '/authentication/sign-in',
  platformProviderSignUpEndpointPath: '/authentication/sign-up',
  platformProviderTripsEndpointPath: '/trips',
  platformProviderIncidentsEndpointPath: '/incidents',
  platformProviderNotificationsEndpointPath: '/notifications',
  platformProviderProfilesEndpointPath: '/profiles',
  platformProviderVehiclesEndpointPath: '/vehicles',
  platformProviderParentsEndpointPath: '/parents',
  platformProviderChildrenEndpointPath: '/children',
  platformProviderDriversEndpointPath: '/drivers',
  platformProviderStudentGroupsEndpointPath: '/student-groups',
  platformProviderPlansEndpointPath: '/plans',
  platformProviderSubscriptionsEndpointPath: '/subscriptions',
  logoProviderApiBaseUrl: 'https://img.logo.dev/',
  logoProviderPublishableKey: 'pk_MaaysUc_QNaCWpZNw7k5UA',
  orsBaseUrl: 'https://api.openrouteservice.org',
  orsApiKey:
    'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjNhMjJlYzkyNWRkMTQyMjJiNTgxYzc1NWRhYWM4NDA1IiwiaCI6Im11cm11cjY0In0=',
  simulationStepMs: 15000,
};
